### ISSUE TITLE
Temp 2 : electric boogaloo

### ISSUE THREAD

**Issue by Pramish-Aryal** [WHN-We-Hate-Nisan/ourBetterGraphics_eyy_.h#11]
Has a few hickups with one of the essential header files i.e. "Essentials.h" ( ͡° ͜ʖ ͡°). Needs to be "headerified"

**Comment by Kuu44** [comment]
Doneth with @0.2

**Comment by Kuu44** [comment]
Essentials.cpp has been created as of @0.2
